export type GameSlug =
  | "mobile-legends"
  | "free-fire"
  | "pubg-mobile"
  | "valorant"
  | "roblox"
  | "genshin-impact"
  | "clash-of-clans"
  | "steam"
  | "point-blank"
  | "call-of-duty-mobile";

export type Product = {
  slug: string;
  title: string;
  game: string;
  gameSlug: GameSlug;
  price: number;
  rank: string;
  level: string;
  server: string;
  platform: string;
  bind: string;
  status: "Ready" | "Sold";
  seller: string;
  sellerSlug: string;
  verified: boolean;
  rating: number;
  sold: number;
  imageKey: number;
  tags: string[];
  description: string;
};

export const adminNumber = "087760337535";

export const games = [
  {
    name: "Mobile Legends",
    slug: "mobile-legends" as const,
    accent: "#2563eb",
    icon: "ML",
    description:
      "Akun ML dengan rank, skin, hero, bind akun, dan status original owner yang jelas sebelum transaksi.",
    filters: ["Rank", "Skin", "Hero", "Level", "Server", "Bind akun", "Original owner"],
    popularRanks: ["Mythic", "Mythical Honor", "Mythical Glory", "Skin Collector"],
    tips: [
      "Pastikan bind Moonton dan email bisa dipindahkan.",
      "Cek jumlah skin dan hero lewat screenshot terbaru.",
      "Jangan konfirmasi selesai sebelum login berhasil.",
    ],
  },
  {
    name: "Free Fire",
    slug: "free-fire" as const,
    accent: "#f97316",
    icon: "FF",
    description: "Cari akun FF sultan, bundle langka, skin gun, rank aktif, dan data bind yang aman.",
    filters: ["Level", "Bundle", "Skin gun", "Rank", "Server", "Bind akun"],
    popularRanks: ["Heroic", "Master", "Evo Gun", "Bundle Rare"],
    tips: ["Minta seller jelaskan status bind.", "Cek bukti bundle dan skin gun.", "Gunakan report kalau data akun tidak sesuai."],
  },
  {
    name: "PUBG Mobile",
    slug: "pubg-mobile" as const,
    accent: "#16a34a",
    icon: "PUBG",
    description: "Akun PUBG Mobile dengan skin senjata, outfit, rank, region, dan akses login yang bisa dicek.",
    filters: ["Rank", "Region", "Skin senjata", "Outfit", "Email access"],
    popularRanks: ["Ace", "Conqueror", "M416 Glacier", "Outfit Premium"],
    tips: ["Cek region sebelum membeli.", "Pastikan email bisa diubah.", "Simpan bukti chat transaksi."],
  },
  {
    name: "Valorant",
    slug: "valorant" as const,
    accent: "#dc2626",
    icon: "VAL",
    description: "Akun Valorant region APAC/EU/NA dengan rank, skin weapon, level, agent, dan email access.",
    filters: ["Rank", "Region", "Skin weapon", "Level", "Agent", "Email access"],
    popularRanks: ["Platinum", "Diamond", "Ascendant", "Vandal Premium"],
    tips: ["Pastikan region cocok.", "Cek akses email penuh.", "Tanyakan riwayat banned atau restriction."],
  },
  {
    name: "Roblox",
    slug: "roblox" as const,
    accent: "#0f172a",
    icon: "RBX",
    description: "Akun Roblox dengan item, avatar, umur akun, email ready, dan riwayat yang lebih mudah diverifikasi.",
    filters: ["Item", "Umur akun", "Email", "Gamepass", "Robux history"],
    popularRanks: ["Limited Item", "Email Ready", "2019 Account", "Avatar Rare"],
    tips: ["Cek akses email.", "Pastikan item sesuai screenshot.", "Jangan lanjut kalau seller minta transfer luar web."],
  },
  {
    name: "Genshin Impact",
    slug: "genshin-impact" as const,
    accent: "#7c3aed",
    icon: "GI",
    description: "Akun Genshin dengan AR, karakter bintang lima, weapon, server, pity, dan bind akun transparan.",
    filters: ["Adventure Rank", "Karakter", "Weapon", "Server", "Bind akun"],
    popularRanks: ["AR55+", "Archon", "Weapon 5 Star", "Server Asia"],
    tips: ["Cek server dan bind HoYoverse.", "Minta screenshot karakter terbaru.", "Verifikasi email sebelum selesai."],
  },
  {
    name: "Clash of Clans",
    slug: "clash-of-clans" as const,
    accent: "#b45309",
    icon: "COC",
    description: "Akun COC dengan Town Hall, hero, base, Supercell ID, dan status recovery yang jelas.",
    filters: ["Town Hall", "Hero", "Base", "Supercell ID", "Original owner"],
    popularRanks: ["TH13", "TH14", "TH15", "Hero Tinggi"],
    tips: ["Pastikan Supercell ID bisa dipindahkan.", "Cek level hero.", "Pastikan base sesuai deskripsi."],
  },
  {
    name: "Steam Games",
    slug: "steam" as const,
    accent: "#0284c7",
    icon: "STM",
    description: "Akun Steam dengan library game, inventory, email access, dan status keamanan yang transparan.",
    filters: ["Game library", "Inventory", "Email access", "VAC status", "Region"],
    popularRanks: ["80+ Games", "Inventory Premium", "Full Access", "No VAC"],
    tips: ["Cek VAC status.", "Pastikan email full access.", "Jangan terima akun tanpa bukti library."],
  },
  {
    name: "Point Blank",
    slug: "point-blank" as const,
    accent: "#475569",
    icon: "PB",
    description: "Akun Point Blank dengan pangkat, weapon permanen, item, dan data bind yang rapi.",
    filters: ["Pangkat", "Weapon", "Item", "Email", "Server"],
    popularRanks: ["Colonel", "Weapon Permanent", "Rare Item", "Email Ready"],
    tips: ["Cek weapon permanen.", "Pastikan email bisa diakses.", "Simpan bukti semua klaim seller."],
  },
  {
    name: "Call of Duty Mobile",
    slug: "call-of-duty-mobile" as const,
    accent: "#0891b2",
    icon: "CODM",
    description: "Akun CODM dengan rank, skin mythic/legendary, region, dan akses login yang lengkap.",
    filters: ["Rank", "Skin", "Region", "Level", "Bind akun"],
    popularRanks: ["Legendary", "Mythic Skin", "Grandmaster", "Region Asia"],
    tips: ["Pastikan bind bisa dipindahkan.", "Cek semua skin premium.", "Gunakan escrow sampai akun aman."],
  },
];

export const sellers = [
  {
    name: "Reza Store ID",
    slug: "reza-store-id",
    avatar: "RS",
    verified: true,
    rating: 4.9,
    sales: 126,
    joined: "Maret 2024",
    description: "Menjual akun original owner, data lengkap, aman, dan siap bantu buyer jika ada kendala.",
    games: ["Mobile Legends", "Valorant", "Genshin Impact"],
  },
  {
    name: "LevelUp Hub",
    slug: "levelup-hub",
    avatar: "LH",
    verified: true,
    rating: 4.8,
    sales: 98,
    joined: "Juni 2024",
    description: "Fokus akun rank tinggi dan inventory premium. Semua listing dicek sebelum tayang.",
    games: ["Free Fire", "PUBG Mobile", "COD Mobile"],
  },
  {
    name: "Akun Rapi Nusantara",
    slug: "akun-rapi-nusantara",
    avatar: "AR",
    verified: true,
    rating: 4.9,
    sales: 151,
    joined: "Januari 2024",
    description: "Seller terverifikasi dengan aftersales jelas dan riwayat report bersih.",
    games: ["Steam Games", "Roblox", "Clash of Clans"],
  },
];

export const products: Product[] = [
  {
    slug: "akun-ml-mythic-45-stars-skin-epic-banyak-siap-main",
    title: "Akun ML Mythic 45 Stars, Skin Epic Banyak, Siap Main",
    game: "Mobile Legends",
    gameSlug: "mobile-legends",
    price: 425000,
    rank: "Mythic 45 Stars",
    level: "82",
    server: "Indonesia",
    platform: "Android/iOS",
    bind: "Moonton + Email",
    status: "Ready",
    seller: "Reza Store ID",
    sellerSlug: "reza-store-id",
    verified: true,
    rating: 4.9,
    sold: 38,
    imageKey: 1,
    tags: ["Skin Epic", "Hero 100+", "Original owner"],
    description:
      "Akun siap push rank, skin epic banyak, hero utama lengkap, dan data recovery disiapkan seller. Cocok untuk buyer yang mau langsung main tanpa ribet.",
  },
  {
    slug: "akun-ml-mythical-glory-78-stars-collector-rapi",
    title: "Akun ML Mythical Glory 78 Stars, Collector Rapi",
    game: "Mobile Legends",
    gameSlug: "mobile-legends",
    price: 1150000,
    rank: "Mythical Glory",
    level: "96",
    server: "Indonesia",
    platform: "Android/iOS",
    bind: "Moonton",
    status: "Ready",
    seller: "Reza Store ID",
    sellerSlug: "reza-store-id",
    verified: true,
    rating: 4.9,
    sold: 17,
    imageKey: 2,
    tags: ["Collector", "WR bagus", "Rank tinggi"],
    description: "Akun high rank dengan beberapa skin collector dan hero pool luas. Seller siap bantu proses pindah bind lewat chat transaksi.",
  },
  {
    slug: "akun-ff-sultan-bundle-banyak-level-tinggi",
    title: "Akun FF Sultan Bundle Banyak, Level Tinggi",
    game: "Free Fire",
    gameSlug: "free-fire",
    price: 680000,
    rank: "Heroic",
    level: "72",
    server: "Indonesia",
    platform: "Android",
    bind: "Facebook + Google",
    status: "Ready",
    seller: "LevelUp Hub",
    sellerSlug: "levelup-hub",
    verified: true,
    rating: 4.8,
    sold: 52,
    imageKey: 3,
    tags: ["Bundle rare", "Evo gun", "Level tinggi"],
    description: "Bundle banyak, skin gun aktif, dan rank masih enak untuk push. Data akun dikirim setelah pembayaran masuk escrow.",
  },
  {
    slug: "akun-ff-evo-gun-4-slot-bundle-rare-email-aman",
    title: "Akun FF Evo Gun 4 Slot, Bundle Rare, Email Aman",
    game: "Free Fire",
    gameSlug: "free-fire",
    price: 925000,
    rank: "Master",
    level: "76",
    server: "Indonesia",
    platform: "Android/iOS",
    bind: "Google",
    status: "Sold",
    seller: "LevelUp Hub",
    sellerSlug: "levelup-hub",
    verified: true,
    rating: 4.8,
    sold: 61,
    imageKey: 4,
    tags: ["Evo gun", "Rare bundle", "Sold"],
    description: "Produk sudah sold. Listing tetap ditampilkan sebagai referensi harga dan kualitas seller.",
  },
  {
    slug: "akun-pubg-ace-master-m416-glacier-outfit-premium",
    title: "Akun PUBG Ace Master, M416 Glacier, Outfit Premium",
    game: "PUBG Mobile",
    gameSlug: "pubg-mobile",
    price: 790000,
    rank: "Ace Master",
    level: "69",
    server: "Asia",
    platform: "Android/iOS",
    bind: "Email full access",
    status: "Ready",
    seller: "LevelUp Hub",
    sellerSlug: "levelup-hub",
    verified: true,
    rating: 4.8,
    sold: 29,
    imageKey: 5,
    tags: ["M416", "Outfit premium", "Asia"],
    description: "Akun PUBG dengan skin senjata favorit dan outfit premium. Cocok untuk kolektor dan pemain rank aktif.",
  },
  {
    slug: "akun-valorant-platinum-region-apac-skin-vandal-premium",
    title: "Akun Valorant Platinum Region APAC, Skin Vandal Premium",
    game: "Valorant",
    gameSlug: "valorant",
    price: 540000,
    rank: "Platinum",
    level: "48",
    server: "APAC",
    platform: "PC",
    bind: "Email full access",
    status: "Ready",
    seller: "Reza Store ID",
    sellerSlug: "reza-store-id",
    verified: true,
    rating: 4.9,
    sold: 34,
    imageKey: 6,
    tags: ["Vandal premium", "APAC", "Email access"],
    description: "Rank Platinum, beberapa skin premium, dan email bisa dipindahkan. Seller tidak menerima transaksi di luar platform.",
  },
  {
    slug: "akun-valorant-diamond-phantom-oni-email-full-access",
    title: "Akun Valorant Diamond, Phantom Oni, Email Full Access",
    game: "Valorant",
    gameSlug: "valorant",
    price: 875000,
    rank: "Diamond",
    level: "63",
    server: "APAC",
    platform: "PC",
    bind: "Email full access",
    status: "Ready",
    seller: "Reza Store ID",
    sellerSlug: "reza-store-id",
    verified: true,
    rating: 4.9,
    sold: 21,
    imageKey: 7,
    tags: ["Diamond", "Oni", "Agent banyak"],
    description: "Akun kompetitif dengan skin Phantom Oni dan agent banyak. Detail dikirim lewat chat aman setelah order dibuat.",
  },
  {
    slug: "akun-roblox-item-banyak-email-ready",
    title: "Akun Roblox Item Banyak, Email Ready",
    game: "Roblox",
    gameSlug: "roblox",
    price: 310000,
    rank: "Verified",
    level: "2019 Account",
    server: "Global",
    platform: "PC/Mobile",
    bind: "Email ready",
    status: "Ready",
    seller: "Akun Rapi Nusantara",
    sellerSlug: "akun-rapi-nusantara",
    verified: true,
    rating: 4.9,
    sold: 44,
    imageKey: 8,
    tags: ["Item banyak", "Email ready", "Akun lama"],
    description: "Akun Roblox lama dengan item avatar banyak. Buyer bisa cek detail item sebelum klik transaksi selesai.",
  },
  {
    slug: "akun-genshin-ar57-banyak-bintang-5-server-asia",
    title: "Akun Genshin AR57, Banyak Bintang 5, Server Asia",
    game: "Genshin Impact",
    gameSlug: "genshin-impact",
    price: 1350000,
    rank: "AR57",
    level: "57",
    server: "Asia",
    platform: "PC/Mobile",
    bind: "HoYoverse",
    status: "Ready",
    seller: "Reza Store ID",
    sellerSlug: "reza-store-id",
    verified: true,
    rating: 4.9,
    sold: 19,
    imageKey: 9,
    tags: ["5 Star", "Server Asia", "Weapon bagus"],
    description: "Roster karakter kuat untuk eksplorasi dan abyss. Bind HoYoverse bisa dibantu pindahkan saat transaksi.",
  },
  {
    slug: "akun-coc-th13-rapi-hero-tinggi",
    title: "Akun COC TH13 Rapi, Hero Tinggi",
    game: "Clash of Clans",
    gameSlug: "clash-of-clans",
    price: 620000,
    rank: "TH13",
    level: "183",
    server: "Global",
    platform: "Android/iOS",
    bind: "Supercell ID",
    status: "Ready",
    seller: "Akun Rapi Nusantara",
    sellerSlug: "akun-rapi-nusantara",
    verified: true,
    rating: 4.9,
    sold: 27,
    imageKey: 10,
    tags: ["TH13", "Hero tinggi", "Base rapi"],
    description: "Base rapi, hero tinggi, dan progress upgrade stabil. Data Supercell ID dikirim lewat sistem setelah escrow masuk.",
  },
  {
    slug: "akun-steam-library-80-game-email-full-access",
    title: "Akun Steam Library 80+ Game, Email Full Access",
    game: "Steam Games",
    gameSlug: "steam",
    price: 990000,
    rank: "Level 24",
    level: "24",
    server: "Global",
    platform: "PC",
    bind: "Email full access",
    status: "Ready",
    seller: "Akun Rapi Nusantara",
    sellerSlug: "akun-rapi-nusantara",
    verified: true,
    rating: 4.9,
    sold: 12,
    imageKey: 11,
    tags: ["80+ game", "No VAC", "Inventory ada"],
    description: "Library berisi banyak game populer, email full access, dan status keamanan dijelaskan di chat transaksi.",
  },
  {
    slug: "akun-pb-colonel-weapon-permanent-banyak",
    title: "Akun PB Colonel Weapon Permanent Banyak",
    game: "Point Blank",
    gameSlug: "point-blank",
    price: 455000,
    rank: "Colonel",
    level: "81",
    server: "Indonesia",
    platform: "PC",
    bind: "Email ready",
    status: "Ready",
    seller: "Akun Rapi Nusantara",
    sellerSlug: "akun-rapi-nusantara",
    verified: true,
    rating: 4.8,
    sold: 23,
    imageKey: 12,
    tags: ["Colonel", "Weapon permanent", "Email ready"],
    description: "Akun PB dengan beberapa weapon permanen dan item aktif. Cocok untuk pemain lama yang ingin langsung main.",
  },
  {
    slug: "akun-codm-legendary-skin-mythic-aktif",
    title: "Akun CODM Legendary, Skin Mythic Aktif",
    game: "Call of Duty Mobile",
    gameSlug: "call-of-duty-mobile",
    price: 830000,
    rank: "Legendary",
    level: "150",
    server: "Asia",
    platform: "Android/iOS",
    bind: "Activision + Email",
    status: "Ready",
    seller: "LevelUp Hub",
    sellerSlug: "levelup-hub",
    verified: true,
    rating: 4.8,
    sold: 31,
    imageKey: 13,
    tags: ["Legendary", "Mythic", "Rank aktif"],
    description: "Akun CODM rank aktif dengan skin mythic dan beberapa item premium. Semua transaksi wajib lewat saldo web.",
  },
];

export const testimonials = [
  {
    name: "Dika",
    text: "Beli akun ML lebih tenang karena dana ditahan dulu. Seller kirim data cepat, admin juga responsif waktu aku nanya.",
  },
  {
    name: "Maya",
    text: "Top up manualnya jelas. Total transfer, fee, dan saldo masuk ditulis rapi jadi nggak bingung.",
  },
  {
    name: "Rangga",
    text: "Pernah ada kendala bind akun, buka report langsung dimediasi. Akhirnya selesai tanpa ribut.",
  },
];

export const faqs = [
  ["Apakah saldo langsung masuk setelah transfer?", "Saldo masuk setelah admin memverifikasi bukti transfer. Biasanya dicek sesuai antrean."],
  ["Kenapa dana seller ditahan dulu?", "Dana ditahan di escrow sampai buyer mengecek akun dan transaksi aman. Ini melindungi buyer dan seller."],
  ["Boleh transaksi langsung ke seller?", "Tidak. Semua transaksi harus lewat saldo Alfarezel Market supaya chat, invoice, dan report tercatat."],
  ["Bagaimana kalau akun tidak sesuai?", "Buka report dari order terkait. Admin bisa meminta bukti, menahan dana, refund buyer, atau release ke seller."],
];

export const adminMenus = [
  "Overview",
  "User Management",
  "Seller Management",
  "Product Management",
  "Order Management",
  "Top Up Management",
  "Withdraw Management",
  "Wallet Management",
  "Report & Dispute Center",
  "Chat Monitoring",
  "Game Category Management",
  "Banner & Promotion Management",
  "Voucher Management",
  "Fee Settings",
  "Platform Settings",
  "Admin Logs",
  "Security Center",
  "CMS Pages",
  "Notification Center",
  "Backup/Export Data",
];

export function getGame(slug: string) {
  return games.find((game) => game.slug === slug);
}

export function getProduct(slug: string) {
  return products.find((product) => product.slug === slug);
}

export function productsByGame(slug: string) {
  return products.filter((product) => product.gameSlug === slug);
}
