services:
  - type: web
    name: alfarezel-market
    env: docker
    plan: starter
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_APP_NAME
        value: Alfarezel Market
      - key: NEXT_PUBLIC_APP_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_DEFAULT_USERNAME
        value: alfarez@gmail.com
      - key: ADMIN_DEFAULT_EMAIL
        value: alfarez@gmail.com
      - key: ADMIN_DEFAULT_TEMP_PASSWORD
        sync: false
      - key: ADMIN_TOPUP_NUMBER
        value: "087760337535"
